export const primaryFolder = [
  {
    name: 'Inbox',
    unreadCount: 20,
    imgUrl: "url('../../../assets/icons/inbox_active.svg')",
  },
  {
    name: 'Flagged',
    unreadCount: 0,
    imgUrl: "url('../../../assets/icons/flagged.svg')",
  },
  {
    name: 'Draft',
    unreadCount: 0,
    imgUrl: "url('../../../assets/icons/draft.svg')",
  },
  { name: 'Sent', unreadCount: 0, imgUrl: "url('../../../assets/icons/sent.svg')", },
  {
    name: 'Trash',
    unreadCount: 0,
    imgUrl: "url('../../../assets/icons/trash.svg')",
  },
  { name: 'More', unreadCount: 0, imgUrl: "url('../../../assets/icons/flagged.svg')", },
  
];
export const secondaryFolder = [
  {
    name: 'Office',
    unreadCount: 20,
    imgUrl: 'src/assets/icons/inbox_active.svg',
  },
  {
    name: 'Personal',
    unreadCount: 0,
    imgUrl: 'src/assets/icons/inbox_active.svg',
  },
  {
    name: 'Finance',
    unreadCount: 0,
    imgUrl: 'src/assets/icons/inbox_active.svg',
  },
];
export const inboxMessagesThreadList = [
  {
    senderName: 'Sam Miller',
    senderImgUrl: '',
    senderEmail: 'abc@gmail.com',
    receivedTimeStamp: new Date().getTime(),
    messageSubject: 'Portfolio',
    messageText: 'Stop wasting time looking for files buried in folders. Visually organize all your assets in one place',
    hasAttachments: true,
    attachmentUrls: ['ab', 'bc', 'de'],
  },
  {
    senderName: 'Lily Jones',
    senderImgUrl: '',
    senderEmail: 'abhijha73@gmail.com',
    receivedTimeStamp: 1692870308000,
    messageSubject: 'Invitations',
    messageText: 'Its always a pleasure to have you all at my birthday parties. So, please dont be late for this one.',
    hasAttachments: true,
    attachmentUrls: ['ab', 'bc', 'de', 'ef', 'gh'],
  },
  {
    senderName: 'Smith',
    senderImgUrl: '',
    senderEmail: 'abhijha73@gmail.com',
    receivedTimeStamp: 1692760408000,
    messageSubject: 'Assingment Submission',
    messageText: 'If you want to set up an assignment with additional reviews, you can enable Moderated Grading...',
    hasAttachments: true,
    attachmentUrls: ['ab', ],
  },
  {
    senderName: 'Patrick',
    senderImgUrl: '',
    senderEmail: 'abhijha73@gmail.com',
    receivedTimeStamp: 1692460408000,
    messageSubject: 'Interview Scheduled',
    messageText: 'Hi Mike, thanks for applying for UI/UX Designer. We are reviewing resumes and will follow up in the...',
    hasAttachments: true,
    attachmentUrls: ['ab',],
  },
  {
    senderName: 'Sam Miller',
    senderImgUrl: '',
    senderEmail: 'abc@gmail.com',
    receivedTimeStamp: 1692160408000,
    messageSubject: 'Portfolio',
    messageText: 'Stop wasting time looking for files buried in folders. Visually organize all your assets in one place',
    hasAttachments: true,
    attachmentUrls: ['ab', 'bc', 'de'],
  },
  {
    senderName: 'Lily Jones',
    senderImgUrl: '',
    senderEmail: 'abhijha73@gmail.com',
    receivedTimeStamp: 1691460408000,
    messageSubject: 'Invitations',
    messageText: 'Its always a pleasure to have you all at my birthday parties. So, please dont be late for this one.',
    hasAttachments: true,
    attachmentUrls: ['ab', 'bc', 'de', 'ef', 'gh'],
  },
  {
    senderName: 'Smith',
    senderImgUrl: '',
    senderEmail: 'abhijha73@gmail.com',
    receivedTimeStamp: 1682460408000,
    messageSubject: 'Assingment Submission',
    messageText: 'If you want to set up an assignment with additional reviews, you can enable Moderated Grading...',
    hasAttachments: true,
    attachmentUrls: ['ab', ],
  },
  {
    senderName: 'Patrick',
    senderImgUrl: '',
    senderEmail: 'abhijha73@gmail.com',
    receivedTimeStamp: 1672460408000,
    messageSubject: 'Interview Scheduled',
    messageText: 'Hi Mike, thanks for applying for UI/UX Designer. We are reviewing resumes and will follow up in the...',
    hasAttachments: true,
    attachmentUrls: ['ab',],
  },
  
];
